In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()
import warnings
warnings.filterwarnings('ignore')

In [30]:
data = pd.read_csv("data/data_raw/financial_sample_raw.csv")

In [31]:
data.shape

(700, 16)

In [32]:
data.columns

Index(['Segment', 'Country', ' Product ', ' Discount Band ', 'Units Sold',
       ' Manufacturing Price ', ' Sale Price ', ' Gross Sales ', ' Discounts ',
       '  Sales ', ' COGS ', ' Profit ', 'Date', 'Month Number',
       ' Month Name ', 'Year'],
      dtype='object')

In [33]:
# Rimuovo gli spazi vuoti prima e dopo i nomi di tutte le colonne
data.columns = data.columns.str.strip()

In [34]:
data.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [35]:
# Normalizzo i nomi delle colonne
data.columns = data.columns.str.strip().str.lower().str.replace(' ', '_')

In [36]:
data.head(20)

,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year
0,Government,Canada,Carretera,None,1618.5,$3.00,$20.00,"$32,370.00",$-,"$32,370.00",COGS,"$16,185.00",1/1/2014,1,January,2014
1,Government,Germany,Carretera,None,1321.0,$3.00,$20.00,"$26,420.00",$-,"$26,420.00",COGS,"$13,210.00",1/1/2014,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,$3.00,$15.00,"$32,670.00",$-,"$32,670.00",COGS,"$10,890.00",6/1/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,$3.00,$15.00,"$13,320.00",$-,"$13,320.00",COGS,"$4,440.00",6/1/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,$3.00,$15.00,"$37,050.00",$-,"$37,050.00",COGS,"$12,350.00",6/1/2014,6,June,2014
5,Government,Germany,Carretera,None,1513.0,$3.00,$350.00,"$529,550.00",$-,"$529,550.00",COGS,"$136,170.00",12/1/2014,12,December,2014
6,Midmarket,Germany,Montana,None,921.0,$5.00,$15.00,"$13,815.00",$-,"$13,815.00",COGS,"$4,605.00",3/1/2014,3,March,2014
7,Channel Partners,Canada,Montana,None,2518.0,$5.00,$12.00,"$30,216.00",$-,"$30,216.00",COGS,"$22,662.00",6/1/2014,6,June,2014
8,Government,France,Montana,None,1899.0,$5.00,$20.00,"$37,980.00",$-,"$37,980.00",COGS,"$18,990.00",6/1/2014,6,June,2014
9,Channel Partners,Germany,Montana,None,1545.0,$5.00,$12.00,"$18,540.00",$-,"$18,540.00",COGS,"$13,905.00",6/1/2014,6,June,2014
10,Midmarket,Mexico,Montana,None,2470.0,$5.00,$15.00,"$37,050.00",$-,"$37,050.00",COGS,"$12,350.00",6/1/2014,6,June,2014
11,Enterprise,Canada,Montana,None,2665.5,$5.00,$125.00,"$333,187.50",$-,"$333,187.50",COGS,"$13,327.50",7/1/2014,7,July,2014
12,Small Business,Mexico,Montana,None,958.0,$5.00,$300.00,"$287,400.00",$-,"$287,400.00",COGS,"$47,900.00",8/1/2014,8,August,2014
13,Government,Germany,Montana,None,2146.0,$5.00,$7.00,"$15,022.00",$-,"$15,022.00",COGS,"$4,292.00",9/1/2014,9,September,2014
14,Enterprise,Canada,Montana,None,345.0,$5.00,$125.00,"$43,125.00",$-,"$43,125.00",COGS,"$1,725.00",10/1/2013,10,October,2013
15,Midmarket,United States of America,Montana,None,615.0,$5.00,$15.00,"$9,225.00",$-,"$9,225.00",COGS,"$3,075.00",12/1/2014,12,December,2014
16,Government,Canada,Paseo,None,292.0,$10.00,$20.00,"$5,840.00",$-,"$5,840.00",COGS,"$2,920.00",2/1/2014,2,February,2014
17,Midmarket,Mexico,Paseo,None,974.0,$10.00,$15.00,"$14,610.00",$-,"$14,610.00",COGS,"$4,870.00",2/1/2014,2,February,2014
18,Channel Partners,Canada,Paseo,None,2518.0,$10.00,$12.00,"$30,216.00",$-,"$30,216.00",COGS,"$22,662.00",6/1/2014,6,June,2014
19,Government,Germany,Paseo,None,1006.0,$10.00,$350.00,"$352,100.00",$-,"$352,100.00",COGS,"$90,540.00",6/1/2014,6,June,2014

In [37]:
data.duplicated().sum()

np.int64(0)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   segment              700 non-null    object
 1   country              700 non-null    object
 2   product              700 non-null    object
 3   discount_band        700 non-null    object
 4   units_sold           700 non-null    float64
 5   manufacturing_price  700 non-null    object
 6   sale_price           700 non-null    object
 7   gross_sales          700 non-null    object
 8   discounts            700 non-null    object
 9   sales                700 non-null    object
 10  cogs                 700 non-null    object
 11  profit               700 non-null    object
 12  date                 700 non-null    object
 13  month_number         700 non-null    int64
 14  month_name           700 non-null    object
 15  year                 700 non-null    int64
dtypes: float64(1), int64(2), object(13)
memory usage: 87.6+ KB

In [39]:
# Conversione delle colonne monetarie in float
currency_cols = ['manufacturing_price', 'sale_price', 'gross_sales', 'discounts', 'sales', 'profit']

for col in currency_cols:
    if col in data.columns:
        data[col] = (
            data[col].astype(str)
            .str.replace('$', '', regex=False)
            .str.replace(',', '', regex=False)
            .str.replace('(', '-', regex=False)  # Converte la parentesi aperta in meno
            .str.replace(')', '', regex=False)   # Rimuove la parentesi chiusa
            .str.replace('-', '0', regex=False)
            .str.strip()
        )
        data[col] = pd.to_numeric(data[col], errors='coerce')

In [40]:
data.head()

,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year
0,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.0,32370.0,COGS,16185.0,1/1/2014,1,January,2014
1,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.0,26420.0,COGS,13210.0,1/1/2014,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.0,32670.0,COGS,10890.0,6/1/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.0,13320.0,COGS,4440.0,6/1/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.0,37050.0,COGS,12350.0,6/1/2014,6,June,2014

In [41]:
# Converto la colonna Data in datetime
data['date'] = pd.to_datetime(data['date'])

In [42]:
data.head()

,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year
0,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.0,32370.0,COGS,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.0,26420.0,COGS,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.0,32670.0,COGS,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.0,13320.0,COGS,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.0,37050.0,COGS,12350.0,2014-06-01,6,June,2014

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   segment              700 non-null    object
 1   country              700 non-null    object
 2   product              700 non-null    object
 3   discount_band        700 non-null    object
 4   units_sold           700 non-null    float64
 5   manufacturing_price  700 non-null    float64
 6   sale_price           700 non-null    float64
 7   gross_sales          700 non-null    float64
 8   discounts            700 non-null    float64
 9   sales                700 non-null    float64
 10  cogs                 700 non-null    object
 11  profit               700 non-null    float64
 12  date                 700 non-null    datetime64[ns]
 13  month_number         700 non-null    int64
 14  month_name           700 non-null    object
 15  year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(7), int64(2), object(6)
memory usage: 87.6+ KB

In [44]:
# Calcolo la colonna COGS
data['cogs'] = data['sales'] - data['profit']

In [45]:
data.head()

,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year
0,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

In [46]:
data.sample(20)

,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year
560,Channel Partners,Canada,VTT,High,2109.0,250.0,12.0,25308.0,3036.96,22271.04,6327.0,15944.04,2014-05-01,5,May,2014
617,Government,United States of America,Montana,High,2996.0,5.0,7.0,20972.0,2936.08,18035.92,14980.0,3055.92,2013-10-01,10,October,2013
547,Government,Mexico,Paseo,High,886.0,10.0,350.0,310100.0,37212.00,272888.00,230360.0,42528.00,2014-06-01,6,June,2014
695,Small Business,France,Amarilla,High,2475.0,260.0,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
628,Small Business,United States of America,Carretera,High,1010.0,3.0,300.0,303000.0,42420.00,260580.00,252500.0,8080.00,2014-10-01,10,October,2014
48,Government,France,Amarilla,None,1899.0,260.0,20.0,37980.0,0.00,37980.00,18990.0,18990.00,2014-06-01,6,June,2014
623,Channel Partners,France,Amarilla,High,1393.0,260.0,12.0,16716.0,2340.24,14375.76,4179.0,10196.76,2014-10-01,10,October,2014
240,Government,United States of America,Paseo,Medium,2327.0,10.0,7.0,16289.0,814.45,15474.55,11635.0,3839.55,2014-05-01,5,May,2014
536,Government,Mexico,Carretera,High,886.0,3.0,350.0,310100.0,37212.00,272888.00,230360.0,42528.00,2014-06-01,6,June,2014
191,Small Business,United States of America,Paseo,Low,2918.0,10.0,300.0,875400.0,35016.00,840384.00,729500.0,110884.00,2014-05-01,5,May,2014
491,Government,Canada,Amarilla,High,707.0,260.0,350.0,247450.0,24745.00,222705.00,183820.0,38885.00,2014-09-01,9,September,2014
95,Enterprise,France,VTT,Low,1744.0,250.0,125.0,218000.0,2180.00,215820.00,209280.0,6540.00,2014-11-01,11,November,2014
356,Small Business,United States of America,Amarilla,Medium,1372.0,260.0,300.0,411600.0,28812.00,382788.00,343000.0,39788.00,2014-12-01,12,December,2014
136,Government,Mexico,VTT,Low,1940.0,250.0,350.0,679000.0,13580.00,665420.00,504400.0,161020.00,2013-12-01,12,December,2013
602,Midmarket,Germany,Velo,High,660.0,120.0,15.0,9900.0,1287.00,8613.00,6600.0,2013.00,2013-09-01,9,September,2013
116,Small Business,Canada,Paseo,Low,1916.0,10.0,300.0,574800.0,11496.00,563304.00,479000.0,84304.00,2014-12-01,12,December,2014
77,Enterprise,France,Paseo,Low,787.0,10.0,125.0,98375.0,983.75,97391.25,94440.0,2951.25,2014-06-01,6,June,2014
195,Government,Canada,Paseo,Low,2074.0,10.0,20.0,41480.0,1659.20,39820.80,20740.0,19080.80,2014-09-01,9,September,2014
206,Government,France,VTT,Low,2177.0,250.0,350.0,761950.0,30478.00,731472.00,566020.0,165452.00,2014-10-01,10,October,2014
686,Enterprise,United States of America,Velo,High,2438.0,120.0,125.0,304750.0,45712.50,259037.50,225515.0,33522.50,2013-12-01,12,December,2013

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   segment              700 non-null    object
 1   country              700 non-null    object
 2   product              700 non-null    object
 3   discount_band        700 non-null    object
 4   units_sold           700 non-null    float64
 5   manufacturing_price  700 non-null    float64
 6   sale_price           700 non-null    float64
 7   gross_sales          700 non-null    float64
 8   discounts            700 non-null    float64
 9   sales                700 non-null    float64
 10  cogs                 700 non-null    float64
 11  profit               700 non-null    float64
 12  date                 700 non-null    datetime64[ns]
 13  month_number         700 non-null    int64
 14  month_name           700 non-null    object
 15  year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(2), object(5)
memory usage: 87.6+ KB

In [48]:
data.groupby("country")["sales"]\
    .sum()\
    .sort_values(ascending=False)\
    .map('${:,.2f}'.format)

country
United States of America    $25,029,830.18
Canada                      $24,887,654.89
France                      $24,354,172.29
Germany                     $23,505,340.82
Mexico                      $20,949,352.11
Name: sales, dtype: object

In [49]:
# Reset dell'indice
data = data.reset_index(drop=True)

In [50]:
# Esportazione in CSV senza includere l'indice di pandas
data.to_csv('financial_data.csv', index=False)